# Generated by Django 6.0.1 on 2026-01-10 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empdetails', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='students',
            new_name='employees',
        ),
    ]
